name: Aggregator Daily Task

on:
  schedule:
    # 每天凌晨 2:30 执行（UTC时间，需按你的时区调整）
    - cron: "30 18 * * *"  # UTC+8 为凌晨 2:30
  workflow_dispatch:  # 允许手动触发

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run:Collect subscriptions
        run: python collect.py

      - name: Run:Daily check-in
        run: python checkin.py

      - name: Run:Process and publish subscriptions
        run: python process.py
