name: Aggregator Daily Task

on:
  schedule:
    - cron: "30 18 * * *"  # 北京时间凌晨 2:30
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  GIST_PAT: ${{ secrets.GIST_PAT }}
  GIST_LINK: ${{ secrets.GIST_LINK }}
  CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check environment variables
        run: |
          if [ -z "$GIST_PAT" ]; then
              echo "Error: GIST_PAT is missing"
              exit 1
          fi
          if [ -z "$GIST_LINK" ]; then
              echo "Error: GIST_LINK is missing"
              exit 1
          fi
          LINK_PARTS=$(echo "$GIST_LINK" | awk -F'/' 'NF==2 && $1!="" && $2!=""')
          if [ -z "$LINK_PARTS" ]; then
              echo "Error: GIST_LINK is invalid"
              exit 1
          fi

      - name: Run: Collect subscriptions
        run: python -u subscribe/collect.py --all --overwrite --skip

      - name: Run: Daily check-in
        run: python -u subscribe/collect.py --all --refresh --overwrite --skip

      - name: Run: Process and publish subscriptions
        run: python -u subscribe/process.py --overwrite

      - name: Timestamp
        run: date
